workspace_id: 9cff40b2-3355-4759-998a-7b469fa922f6
workspace_url: https://app.fabric.microsoft.com/groups/9cff40b2-3355-4759-998a-7b469fa922f6/list?experience=fabric-developer
git_folder: workspace
github_repo: Tamadhi/powerbi_automation
branch: main
